### PR TITLE
fix: add a check for the existence of the drift detection manager before upgrade

### LINKED ISSUE #1742: BUG: drift detection manager is installed erroneously on addon-controller restart for non drift detection clusters
# Problem Description

``
If a sveltos cluster does not have drift detection enabled and the addon controller is restarted then the drift-detection-manager deployment is created because the skipUpgrading function does not ensure that a cluster actually has drift detection enabled. This is because skipUpgrading just checks for the existence of the ResourceSummary CRD but not whether the drift detection is actually deployed.
``

# System Information

CLUSTERAPI VERSION: `1.12.5`
SVELTOS VERSION: ` 1.8.0`
KUBERNETES VERSION: `1.33.1`

### PR DESCRIPTION
**Pull request by kylewuolle**
This change adds a check that the drift detection manager is actually installed before proceeding with an upgrade. Otherwise, the upgrade ends up installing it. 

Fixes #1742

### CODE REVIEW

File: controllers/drift_detection_upgrade.go [hunk 1]
```diff
@@ -296,7 +296,12 @@ func skipUpgrading(ctx context.Context, c client.Client, cluster client.Object,
 		return true, err
 	}
 
-	// Verify if ResourceSummary CRD is present. Th
+	_, hasDrift := clustersWithDriftDetection[*clusterRef]
```
Comment (gianlucam76) [inline controllers/drift_detection_upgrade.go]: We use the clustersWithDriftDetection for pullMode clusters since we cannot verify the presence of driftDetection manager  on those clusters.

For push mode we should simply rely on isDriftDetectionManagerDeployedInCluster verification. 

The drift-detection-manager gets deployed the first time a profile with syncMode: ContinuousWithDriftDetection matches that cluster. 
There is no code after that to remove it (too complex to do ref counting consistently).

If a drift-detection-manager deployment is present on a managed cluster we want to upgrade it. And it can happen on upgrade drift-detection-manager is present on the cluster but there are currently no more clusterSummary in drift detection mode matching such a cluster.

Skipping the upgrade might bring incompatible versions between management cluster and that managed cluster.

So here the check should rely only on isDriftDetectionManagerDeployedInCluster.

**Review by gianlucam76 — COMMENTED** [review]
Thank you for pushing the fix (and before that root causing the issue)!

I have a minor comment that simply requires using isDriftDetectionManagerDeployedInCluster to detect in an upgrade is necessary for push mode.

After that we can merge this. Thank you!

File: controllers/drift_detection_upgrade.go (hunk 1 above)
Comment (gianlucam76) [reply controllers/drift_detection_upgrade.go]: If we want to be more aggressive potentially for push mode cluster we could say that:

1. if isDriftDetectionManagerDeployedInCluster returns true &&
2. hasDrift is false

then delete the drift-detection-manager deployment. Your call if you want to extend PR. I think what you already have (after taking care of my comment) is all we need. 

Thank you again

File: controllers/drift_detection_upgrade.go [hunk 2]
```diff
@@ -309,6 +314,18 @@ func skipUpgrading(ctx context.Context, c client.Client, cluster client.Object,
 	return false, nil
 }
 
+func isDriftDetectionManagerDeployedInCluster(ctx context.Context, c client.Client) bool {
+	deployments := &appsv1.DeploymentList{}
+	listOptions := []client.ListOption{
+		client.InNamespace(projectsveltos),
+		client.MatchingLabels{driftDetectionFeatureLabelKey: driftDetectionFeatureLabelValue},
```
Comment (zerospiel) [inline controllers/drift_detection_upgrade.go]:
```suggestion
		client.InNamespace(projectsveltos),
		client.Limit(1),
		client.MatchingLabels{driftDetectionFeatureLabelKey: driftDetectionFeatureLabelValue},
```

Since we check a mere "were there any such deployments", it might be worth limiting the number of objects to 1, just to ensure we avoid any extra work (API/network/deserialization)

Comment (gianlucam76) [reply controllers/drift_detection_upgrade.go]: we can do that.

Alternatively we can (once) call [GetDriftDetectionManagerYAML](https://github.com/projectsveltos/addon-controller/blob/1b92aa13170b9d7e1a5d7a2224820516c0bcf7fb/pkg/drift-detection/drift_manager.go#L23) and get the unstructured.Unstructured of the deployment, and then do a Get instead of a List. 

But I can make this change as a separate PR since the goal of this PR is to fix Sveltos creating the drift-detection-manager on restart in the management cluster. @kylewuolle decision.

Thanks

File: controllers/drift_detection_upgrade.go (hunk 1 above)
Comment (kylewuolle) [reply controllers/drift_detection_upgrade.go]: Done!

File: controllers/drift_detection_upgrade.go (hunk 2 above)
Comment (kylewuolle) [reply controllers/drift_detection_upgrade.go]: I've changed it to a get instead, hopefully this makes more sense here.

**Review by gianlucam76 — APPROVED** [review]
LGTM. Thank you
